### ISSUE TITLE
Per-step output variables

### ISSUE THREAD

**Issue by Lucide** [saulmaldonado/skip-workflow#58]
Hi, would it be possible to allow the user to choose arbitrary output variables?
I'd like to be able to selectively enable multiple jobs using commit message switches, like `#docs` to enable the documentation job, `#tests` to run tests, ecc. It often happens that little edits trigger unwanted rebuilds (like documentation builds, which can take a lot of time).

I think this is already achievable in "step mode", with flipped `if: ${{ steps.skip-workflow.outputs.skip }}` on the steps.
But in "job mode", that can't be done because the `outputs` are global, and fixed. I'd like to have a single job that sets various `skip` variables for every step that calls the action. Is that possible? I've never seen it done by similar actions.

**Comment by saulmaldonado** [comment]
Hey there!

I understand what you are trying to do. The action a outputs a single value with the ID `skip` which can then be used in the context of its current job or other downstream jobs ( jobs that contain the `jobs.<job_id>.needs` field ) to dynamically run other steps. 

There isn't a way to output multiple values from a single run of the action so if you need different outputs for different switches like `#docs` or `#test` you would need to run the action for each switch you want to check for. You can do this all in a single job where every job corresponds to a different action run with a different switch to search for. Then once you export these output values to downstream jobs, you can give them a unique output ID to reference them later.

For example:
```sh
jobs:
  skip-workflow:
    runs-on: ubuntu-latest
    outputs:
   # assigning outputs new ID for downstream jobs
      docs: ${{ steps.docs.outputs.skip }} 
      tests: ${{ steps.tests.outputs.skip }} 
      # these outputs can be accessed in downstream jobs as 'needs.skip-workflow.outputs.docs' 
      # and 'needs.skip-workflow.outputs.tests'

    steps:
    - id: docs # searches for '#docs'
      uses: saulmaldonado/skip-workflow@v1 
      with:
          phrase: '#docs'
          github-token: ${{ secrets.GITHUB_TOKEN }}

    - id: tests # searches for '#tests'
      uses: saulmaldonado/skip-workflow@v1
      with:
          phrase: '#tests'
          github-token: ${{ secrets.GITHUB_TOKEN }}

  docs:
    runs-on: ubuntu-latest
    needs: skip-workflow # indicates that this is a downstream job
    if: ${{ needs.skip-workflow.outputs.docs }} # output for the '#docs' switch
   ...
```

Really all this action does is search for phrases/patterns in commit message and output a `true` or `false` variable depending on if a match was found. The whole skipping of jobs has to be implemented at the workflow level so this can actually be used for general purposes. Let me know if you have any other questions!

**Comment by Lucide** [comment]
Oh that's amazing, I didn't realize the `id` could do that!
One minor issue: there appears to be no tag for the "1" version, only for full versions like "1.0.0" or "1.1.0".
